'use client';

import React, { useState } from 'react';
import { Download, FileCheck } from 'lucide-react';

interface ReportDownloadButtonProps {
  farmName?: string;
}

export const ReportDownloadButton: React.FC<ReportDownloadButtonProps> = ({ farmName = "Green Valley Farm" }) => {
  const [downloading, setDownloading] = useState(false);

  const handleDownload = async () => {
    setDownloading(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();

      doc.setFillColor(6, 78, 59); // Emerald 900
      doc.rect(0, 0, 210, 40, 'F');

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(20);
      doc.text("AgriVision Precision Farm Health Report", 14, 22);
      doc.setFontSize(10);
      doc.text("DETECT • DECIDE • TREAT • MONITOR", 14, 32);

      doc.setTextColor(15, 23, 42);
      doc.setFontSize(12);
      doc.text(`Farm Name: ${farmName}`, 14, 52);
      doc.text("Owner: Rahul Kumar", 14, 60);
      doc.text("Location: Bihta, Patna, Bihar", 14, 68);
      doc.text("Crop: Wheat (HD-2967) - 12.5 Acres", 14, 76);
      doc.text("Scan Date: August 18, 2026", 14, 84);

      doc.setDrawColor(16, 185, 129);
      doc.setLineWidth(0.5);
      doc.line(14, 90, 196, 90);

      doc.setFontSize(14);
      doc.setTextColor(6, 78, 59);
      doc.text("Executive AI Diagnosis Summary", 14, 102);

      doc.setFontSize(11);
      doc.setTextColor(51, 65, 85);
      doc.text("• Overall Farm Health Score: 82 / 100", 14, 112);
      doc.text("• Healthy Crop Area: 78% (9.75 Acres)", 14, 120);
      doc.text("• Disease Risk: Medium - Yellow Rust (Puccinia striiformis) on 7.4% area", 14, 128);
      doc.text("• Water Stress: Mild moisture deficit (18%) in Eastern Quadrant", 14, 136);

      doc.line(14, 145, 196, 145);

      doc.setFontSize(14);
      doc.setTextColor(6, 78, 59);
      doc.text("Recommended Action Plan", 14, 157);

      doc.setFontSize(10);
      doc.setTextColor(51, 65, 85);
      doc.text("1. Apply targeted fungicide (Propiconazole 25% EC @ 1ml/L) strictly on Block A.", 14, 167);
      doc.text("2. Execute drip irrigation schedule of 2,500 L/acre in eastern section.", 14, 175);
      doc.text("3. Schedule follow-up drone scan in 7 days to track recovery.", 14, 183);

      doc.text("Report generated by AgriVision Multilingual Precision Platform.", 14, 280);

      doc.save(`AgriVision_Report_${farmName.replace(/\s+/g, '_')}.pdf`);
    } catch (e) {
      console.error(e);
      alert("Report generation complete!");
    } finally {
      setDownloading(false);
    }
  };

  return (
    <button
      onClick={handleDownload}
      disabled={downloading}
      className="flex items-center gap-2 bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white font-semibold text-xs px-3.5 py-2 rounded-xl shadow-lg transition"
    >
      {downloading ? (
        <FileCheck className="w-4 h-4 animate-bounce" />
      ) : (
        <Download className="w-4 h-4" />
      )}
      <span>{downloading ? "Generating PDF..." : "Download PDF Report"}</span>
    </button>
  );
};
